# Your workflow name.
name: Deploy to Render.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
    